<a href="https://colab.research.google.com/github/arunkumarpallala/fmml2021/blob/main/10_Problem_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Madagascar problem

In [1]:
import numpy as np

In [15]:
A = np.array([[20, 122, 20], [35,180, 35],[50, 220, 65], [70, 300, 30]])
x = np.array([[0.05], [0.002], [0.02]])
print(A)
print("==========")
print(x)

[[ 20 122  20]
 [ 35 180  35]
 [ 50 220  65]
 [ 70 300  30]]
[[0.05 ]
 [0.002]
 [0.02 ]]


In [21]:
# 4x3 . 3x1 = 4x1
y = np.matmul(A,x)
print(y)

[[1.644]
 [2.81 ]
 [4.24 ]
 [4.7  ]]


In [22]:
y = np.matmul(A,x) - 4.0
print(y)

[[-2.356]
 [-1.19 ]
 [ 0.24 ]
 [ 0.7  ]]


In [30]:
Z = np.hstack((A,y))

In [28]:
Z

array([[ 2.000e+01,  1.220e+02,  2.000e+01, -2.356e+00],
       [ 3.500e+01,  1.800e+02,  3.500e+01, -1.190e+00],
       [ 5.000e+01,  2.200e+02,  6.500e+01,  2.400e-01],
       [ 7.000e+01,  3.000e+02,  3.000e+01,  7.000e-01]])

In [19]:
def RankArray(A,x):
  y = np.dot(A,x) - 4.0
  L = np.hstack((A,y))
  return L

In [20]:
print (RankArray(A,x))

[[ 2.000e+01  1.220e+02  2.000e+01 -2.356e+00]
 [ 3.500e+01  1.800e+02  3.500e+01 -1.190e+00]
 [ 5.000e+01  2.200e+02  6.500e+01  2.400e-01]
 [ 7.000e+01  3.000e+02  3.000e+01  7.000e-01]]


In [13]:
import numpy as np
a = np.array([[1,2],[2,3]])
b = np.array(([8,4],[4,7]))
print(a,"\n",b)
c=np.dot(a,b)
print("---------------")
print(c)
c1=np.matmul(a,b)
print("---------------")
print(c1)
c2=4*np.dot(a,b)
print("---------------")
print(c2)
c3=4*np.matmul(a,b)
print("---------------")
print(c3)


[[1 2]
 [2 3]] 
 [[8 4]
 [4 7]]
---------------
[[16 18]
 [28 29]]
---------------
[[16 18]
 [28 29]]
---------------
[[ 64  72]
 [112 116]]
---------------
[[ 64  72]
 [112 116]]
